Repository ansible-middleware/jws, pull requests merged in 2022-04, with the labels that each got.

#67 changelog generation setup
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .gitignore
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/config.yaml
  changelogs/fragments/.gitignore
  docs/CHANGELOG.rst
  docs/_gh_include/footer.inc
  docs/index.rst
  docs/releasing.md
  docs/roles.rst.template
  galaxy.yml
Labels: documentation

#80 If another tomcat is found running, fail fast or allow to continue with `tomcat_force_install`
  .ansible-lint
  molecule/force_install/converge.yml
  molecule/force_install/molecule.yml
  molecule/force_install/prepare.yml
  molecule/force_install/roles
  molecule/force_install/verify.yml
  roles/jws/README.md
  roles/jws/defaults/main.yml
  roles/jws/meta/argument_specs.yml
  roles/jws/tasks/install/force_install.yml
  roles/jws/tasks/main.yml
  roles/jws/tasks/uninstall.yml
Labels: minor_changes

#92 docs: update for rhn_zipfiles method
  README.md
  playbook.yml
  roles/jws/tasks/install/rhn.yml
Labels: documentation

#97 The JWS installation option should allow you to exclude natives
  README.md
  roles/jws/README.md
  roles/jws/defaults/main.yml
  roles/jws/meta/argument_specs.yml
  roles/jws/tasks/install/fetch_zipfile_from_rhn_and_deploy.yml
  roles/jws/tasks/install/rhn.yml
  roles/jws/tasks/install/zipfiles.yml
Labels: bugfixes

#101 Ensure JAVA_HOME is set to installed JVM rpm, or allow to override
  molecule/force_install/converge.yml
  roles/jws/README.md
  roles/jws/meta/argument_specs.yml
  roles/jws/tasks/java_install.yml
  roles/jws/tasks/systemd/systemd.yml
  roles/jws/templates/systemd/tomcat.conf.j2
Labels: bugfixes

#100 fix: tomcat.user owning existing directories
  roles/jws/tasks/main.yml
Labels: bugfixes
