Repository ansible-middleware/jws, pull requests merged in 2022-05, with the labels that each got.

#106 Adjustments to the apply_cp.yml logic
  roles/jws/tasks/apply_cp.yml
Labels: bugfixes

#110 Populate JWS version/patch metadata, update docs
  README.md
  roles/jws/README.md
  roles/jws/vars/main.yml
Labels: minor_changes

#112 Make selinux policy for JWS optional like the zip installation docs suggest it is
  roles/jws/README.md
  roles/jws/defaults/main.yml
  roles/jws/meta/argument_specs.yml
  roles/jws/tasks/main.yml
Labels: bugfixes

#117 Rename variables to be consistent
  .ansible-lint
  roles/jws/README.md
  roles/jws/defaults/main.yml
  roles/jws/meta/argument_specs.yml
  roles/jws/tasks/main.yml
  roles/jws/vars/main.yml
Labels: breaking_changes

#118 Avoid failure when `jws_apply_patches` is true and no CP is available
  roles/jws/tasks/main.yml
  roles/jws/vars/main.yml
Labels: bugfixes

#119 selinux policy allows tomcat to listen to non-default ports
  roles/jws/tasks/systemd/selinux.yml
Labels: bugfixes

#121 `jws_apply_patches` also installs native CP when available
  roles/jws/tasks/apply_cp.yml
  roles/jws/vars/main.yml
Labels: bugfixes
