Repository ansible-middleware/jws, pull requests merged in 2024-11, with the labels that each got.

#281 AMW-339 JWS 5.8.0 release missing from README
  roles/jws/README.md
Labels: documentation, minor_changes

#282 add check for validity of patch download suffix
  roles/jws/tasks/apply_cp/download_from_rhn.yml
Labels: internal

#287 AMW-333 - jws roles description missing from README
  README.md
Labels: documentation

#288 AMW-335 - jws_native set to False by default in README
  README.md
Labels: documentation
